import Head from 'next/head'

const sections = [
  { title: 'Not medical advice', body: 'This tool provides informational output only and does not constitute medical advice, diagnosis, or treatment.' },
  { title: 'Not a diagnostic tool', body: 'Outputs are generated by AI based on user input and are not a substitute for professional clinical evaluation.' },
  { title: 'No doctor-patient relationship', body: 'Use of this app does not create a doctor-patient relationship with any party.' },
  { title: 'Not for emergencies', body: 'Do not use this tool for urgent or emergent situations. Call 911 or your local emergency services if you experience urgent symptoms.' },
  { title: 'Consult qualified professionals', body: 'Always consult a licensed healthcare professional for questions about your health or medical conditions.' },
  { title: 'Informational only', body: 'All content is for general informational purposes. Do not rely on it to make medical decisions.' },
]

export default function TermsPage() {
  return (
    <>
      <Head>
        <title>Terms &amp; Disclaimer | MedRoute</title>
        <meta name="description" content="MedRoute terms and medical disclaimer" />
      </Head>
      <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-16 px-4">
        <div className="max-w-3xl mx-auto bg-white/90 backdrop-blur shadow-xl rounded-2xl border border-gray-100 p-10">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms &amp; Disclaimer</h1>
          <p className="text-sm text-gray-600 mb-8">
            MedRoute is an informational tool. It is not a medical device, does not diagnose or treat conditions, and is not a substitute for professional medical advice.
          </p>
          <div className="space-y-6">
            {sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-xl font-semibold text-gray-900">{section.title}</h2>
                <p className="text-sm text-gray-700 mt-2 leading-relaxed">{section.body}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
